DEVICE_KERNEL_PATH := device/amazon/mt8135-kernel

# Boot Image
ifeq ($(TARGET_HAS_LOCKED_BOOTLOADER),true)
BOARD_CUSTOM_BOOTIMG := true
BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_KERNEL_PATH)/mkbootimg.mk
TARGET_PREBUILT_BOOTIMAGE := $(DEVICE_KERNEL_PATH)/boot-$(TARGET_DEVICE).img
endif

BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_SECOND_OFFSET := 0x00f00000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)

# Kernel
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL := $(DEVICE_KERNEL_PATH)/zImage-$(TARGET_DEVICE)
